version: '3.8'

services:
  supafund-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app:/app/gnosis_predict_market_tool
      - PYTHONUNBUFFERED=1
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./gnosis_predict_market_tool:/app/gnosis_predict_market_tool
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  supafund-agent-dev:
    build: .
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app:/app/gnosis_predict_market_tool
      - PYTHONUNBUFFERED=1
      - PORT=8000
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped