# Railway Nixpacks configuration for Supafund Market Creation Agent

[variables]
PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
PYTHONPATH = "."

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "poetry"]

[phases.install] 
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd gnosis_predict_market_tool && poetry install --no-dev",
  "cd .."
]

[start]
cmd = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"