name: Deploy to AWS App Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run health check test
      run: |
        python -c "
        import sys
        sys.path.append('src')
        try:
            from main import app
            print('✅ App imports successfully')
        except Exception as e:
            print(f'❌ Import error: {e}')
            sys.exit(1)
        "
    
    - name: Test blockchain module availability
      run: |
        python -c "
        import sys
        sys.path.append('src')
        try:
            from blockchain.market_creator import create_omen_market
            print('✅ Blockchain module imports successfully')
        except Exception as e:
            print(f'⚠️ Blockchain module warning: {e}')
        "

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy notification
      run: |
        echo "🚀 Deployment will be handled automatically by AWS App Runner"
        echo "✅ Tests passed, AWS App Runner will pull and deploy the latest changes"